[package]
name = "trivial-api"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["full", "macros", "rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = "0.3"
