name: deploy trivial-api

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: Reasonable-Solutions/git-at-home/action@master
        with:
          git_repo: https://github.com/Reasonable-Solutions/trivial-api.git
          git_ref: master
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
